### ISSUE TITLE
time to update to the latest ADT?

### ISSUE THREAD

**Issue by jaimeiniesta** [accesslint/access_lint#12]
The [ADT wiki](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules) lists far more audit rules that don't seem to be covered on access_lint.

I'd like to update to the latest ADT, as it has not been updated since December. Is it OK to do that? Should we leave out some of the audit rules?

**Comment by ckundo** [comment]
@jaimeiniesta this sounds good to me. PRs welcome!

**Comment by jaimeiniesta** [comment]
Alright, will do -- can I include all audit rules in ADT, or should I exclude some of them?

**Comment by ckundo** [comment]
Let's include all of them.

**Comment by jaimeiniesta** [comment]
I'm not sure where to get the latest rules from: on the [ADT Readme](https://github.com/GoogleChrome/accessibility-developer-tools) it tells to get them from the [stable](https://raw.github.com/GoogleChrome/accessibility-developer-tools/stable/dist/js/axs_testing.js) branch, but this is almost one year old now -- I have tried to use that but then it only has 14 rules (we currently have 17). I have also looked at the latest release, v0.0.5, but is also one year old.

Should we take it just from the master branch? Wait for a release or a new merge to stable?

**Comment by ckundo** [comment]
That Readme is out of date, I’ve been pulling from master.

**Comment by jaimeiniesta** [comment]
The `axs_testing.js` file on the master branch is the same as the one in stable, it looks like it corresponds to the latest release.

I've tried to build it, but there seems to be an issue with that:

https://github.com/GoogleChrome/accessibility-developer-tools/issues/144

**Comment by jaimeiniesta** [comment]
The issue was fixed so I could build it.

Here's the PR https://github.com/accesslint/access_lint/pull/13
