### ISSUE TITLE
Unexpected token at null (AccessLint::ParserError)

### ISSUE THREAD

**Issue by arthur24b6** [accesslint/access_lint#16]
Hi- thanks for your work on this. I'm running the cc-print branch because I want the exit code status for my testing suite. I'm guessing that my error is environmental but am wondering if you have any insight into this: `access_lint/lib/access_lint/audit.rb:33:in `rescue in parse_output': 757: unexpected token at 'null (AccessLint::ParserError)'` This error is not thrown on the master branch.

The full error is:
```
$ access_lint audit http://google.com
auditing http://google.com
/home/ubuntu/access_lint/lib/access_lint/audit.rb:33:in `rescue in parse_output': 757: unexpected token at 'null (AccessLint::ParserError)
'
	from /home/ubuntu/access_lint/lib/access_lint/audit.rb:29:in `parse_output'
	from /home/ubuntu/access_lint/lib/access_lint/audit.rb:25:in `perform_audit'
	from /home/ubuntu/access_lint/lib/access_lint/audit.rb:13:in `run'
	from /home/ubuntu/access_lint/lib/access_lint/cli.rb:14:in `block in audit'
	from /home/ubuntu/.rvm/gems/ruby-2.2.3/gems/command_line_reporter-3.3.6/lib/command_line_reporter/formatter/nested.rb:29:in `call'
	from /home/ubuntu/.rvm/gems/ruby-2.2.3/gems/command_line_reporter-3.3.6/lib/command_line_reporter/formatter/nested.rb:29:in `format'
	from /home/ubuntu/.rvm/gems/ruby-2.2.3/gems/command_line_reporter-3.3.6/lib/command_line_reporter.rb:55:in `report'
	from /home/ubuntu/access_lint/lib/access_lint/cli.rb:13:in `audit'
	from /home/ubuntu/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/ubuntu/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ubuntu/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/ubuntu/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/ubuntu/access_lint/bin/access_lint:9:in `<top (required)>'
	from /home/ubuntu/.rvm/gems/ruby-2.2.3/bin/access_lint:23:in `load'
	from /home/ubuntu/.rvm/gems/ruby-2.2.3/bin/access_lint:23:in `<main>'
	from /home/ubuntu/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/ubuntu/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ckundo** [comment]
Hey @arthur24b6, thanks for reporting this. I suspect this is an issue with parsing a null response from the phatomjs audit.js script. I'll investigate!

**Comment by ckundo** [comment]
@arthur24b6 I bundled the wrong file for the testing library, I'll update it in a few.

**Comment by arthur24b6** [comment]
Thanks for such a quick reply. I think this could be a version of phantomjs- it looks like it works for me under 1.9.0 but not under 1.9.8. I'm going to do a bit more poking to make sure that that is the case.

**Comment by arthur24b6** [comment]
Well looks like I was wrong- I tried downgrading to phantom 1.9.0 on the environment where it was failing and the same error crops up.

**Comment by ckundo** [comment]
@arthur24b6 please pull the latest version of `cc-print` and try again.

**Comment by arthur24b6** [comment]
Fantastic, works like a charm. Thank you very much for such a fast response!
